export const lantaiData = [
  {
    id: 0,
    name: "Lantai 1",
    denahUrl: "/panos/denah/Denah_lt1.jpeg",
    ruangan: [
      {
        loc: "R. tunggu",
        url: "",
        hotspot: [],
        position: { x: 34.5, y: 33.5 },
      },
      { loc: "IPVJ", url: "", hotspot: [], position: { x: 43.5, y: 27.5 } },
      {
        loc: " OLAH DATA",
        url: "",
        hotspot: [],
        position: { x: 43.5, y: 30 },
      },
      {
        loc: " REKAM MEDIK",
        url: "",
        hotspot: [],
        position: { x: 49, y: 29 },
      },
      {
        loc: " server",
        url: "",
        hotspot: [],
        position: { x: 53, y: 27 },
      },
      {
        loc: " Simrs",
        url: "",
        hotspot: [],
        position: { x: 53, y: 30.5 },
      },

      {
        loc: "Loket ",
        url: "",
        hotspot: [],
        position: { x: 39, y: 29 },
      },
      {
        loc: "R.Konsultasi",
        url: "",
        hotspot: [],
        position: { x: 40, y: 34.5 },
      },
      { loc: "Adm", url: "", hotspot: [], position: { x: 44, y: 33.8 } },
      {
        loc: "sitostatika ",
        url: "",
        hotspot: [],
        position: { x: 47.5, y: 34.5 },
      },
      {
        loc: "Non sitostatika ",
        url: "",
        hotspot: [],
        position: { x: 51.5, y: 35 },
      },
      {
        loc: "Kepala Farmasi",
        url: "",
        hotspot: [],
        position: { x: 46.8, y: 37 },
      },
      {
        loc: "PENYIMPANAN AMHP/BMHP",
        url: "",
        hotspot: [],
        position: { x: 53, y: 34.5 },
      },
      { loc: "Apotek", url: "", hotspot: [], position: { x: 40.5, y: 36.5 } },

      { loc: "Lift", url: "", hotspot: [], position: { x: 40.5, y: 43 } },
      { loc: "R. Panel", url: "", hotspot: [], position: { x: 47.9, y: 42 } },
      { loc: "R. Staff", url: "", hotspot: [], position: { x: 47.8, y: 45 } },
      { loc: "ICT", url: "", hotspot: [], position: { x: 51, y: 43 } },
      { loc: "R. Isolasi", url: "", hotspot: [], position: { x: 53, y: 43 } },
      {
        loc: "R.Dekontaminasi",
        url: "",
        hotspot: [],
        position: { x: 55.5, y: 44.5 },
      },
      { loc: "Strecher", url: "", hotspot: [], position: { x: 59, y: 43 } },
      {
        loc: "R.Depo Farmasi",
        url: "",
        hotspot: [],
        position: { x: 48.8, y: 47.5 },
      },
      { loc: "Triase", url: "", hotspot: [], position: { x: 53.5, y: 48.5 } },
      { loc: "R.Adm", url: "", hotspot: [], position: { x: 55.9, y: 51 } },
      { loc: "Scrub-Up", url: "", hotspot: [], position: { x: 44.5, y: 54.5 } },
      {
        loc: "R.OK Cito",
        url: "",
        hotspot: [],
        position: { x: 43.5, y: 57.5 },
      },
      { loc: "R.Bedah", url: "", hotspot: [], position: { x: 51, y: 55.5 } },
      {
        loc: "R.Resusitasi",
        url: "",
        hotspot: [],
        position: { x: 56.5, y: 54.7 },
      },
      {
        loc: "R.AHU OK CITO",
        url: "",
        hotspot: [],
        position: { x: 61.4, y: 56 },
      },
      {
        loc: "Radiologi",
        url: "",
        hotspot: [],
        position: { x: 43.5, y: 64.5 },
      },
      {
        loc: "R.Xray",
        url: "",
        hotspot: [],
        position: { x: 48.5, y: 69 },
      },
      {
        loc: "R.Kontrol",
        url: "",
        hotspot: [],
        position: { x: 52.2, y: 69 },
      },
      { loc: "R.Adm", url: "", hotspot: [], position: { x: 50.5, y: 63.5 } },
      { loc: "R.Hasil", url: "", hotspot: [], position: { x: 50, y: 66 } },
      { loc: "R.Proses", url: "", hotspot: [], position: { x: 52, y: 66 } },
      { loc: "R.Kantor", url: "", hotspot: [], position: { x: 37, y: 64 } },
      {
        loc: "R.Storing",
        url: "",
        hotspot: [],
        position: { x: 33.3, y: 63.7 },
      },
      {
        loc: "R. Packaging",
        url: "",
        hotspot: [],
        position: { x: 32.6, y: 69 },
      },
      { loc: "R.Steril", url: "", hotspot: [], position: { x: 37.8, y: 69 } },
      {
        loc: "R.Gudang Farmasi",
        url: "",
        hotspot: [],
        position: { x: 37.5, y: 74.2 },
      },
      {
        loc: "R. Penyimpanan AHMP dan BHMP",
        url: "",
        hotspot: [],
        position: { x: 33, y: 72 },
      },
      {
        loc: "R. Penyimpanan Obat",
        url: "",
        hotspot: [],
        position: { x: 33, y: 75.5 },
      },
      {
        loc: "R. Penyimpanan Cair",
        url: "",
        hotspot: [],
        position: { x: 33, y: 78 },
      },
      {
        loc: "R. Gas Medis",
        url: "",
        hotspot: [],
        position: { x: 33, y: 80.7 },
      },

      { loc: "R.Tunggu", url: "", hotspot: [], position: { x: 43, y: 72 } },
      {
        loc: "Poli Eksekutif",
        url: "",
        hotspot: [],
        position: { x: 51, y: 76.5 },
      },
      { loc: "toilet", url: "", hotspot: [], position: { x: 42, y: 78 } },
    ],
  },

  {
    id: 1,
    name: "Lantai 2",
    denahUrl: "/panos/denah/Denah_lt2.jpeg",
    ruangan: [
      {
        loc: "R. Direktur Utama",
        url: "",
        hotspot: [],
        position: { x: 6, y: 56 },
      },
      { loc: "TU", url: "", hotspot: [], position: { x: 15, y: 60 } },
      { loc: "Bendahara", url: "", hotspot: [], position: { x: 24, y: 55 } },
      {
        loc: "R. Komite Kepegawaian",
        url: "",
        hotspot: [],
        position: { x: 24, y: 62 },
      },
      {
        loc: "R. Sekertaris ",
        url: "",
        hotspot: [],
        position: { x: 23, y: 70 },
      },
      {
        loc: "R. Direksi ",
        url: "",
        hotspot: [],
        position: { x: 20, y: 79.5 },
      },
      {
        loc: "R. Direksi ",
        url: "",
        hotspot: [],
        position: { x: 15, y: 79.5 },
      },
      {
        loc: "R. Direksi ",
        url: "",
        hotspot: [],
        position: { x: 11, y: 79.5 },
      },
      {
        loc: "R. Meeting ",
        url: "",
        hotspot: [],
        position: { x: 6, y: 79.5 },
      },
      { loc: "Musholla", url: "", hotspot: [], position: { x: 6, y: 85.5 } },
      { loc: "Toilet", url: "", hotspot: [], position: { x: 16.5, y: 87 } },
      { loc: "R. Tunggu ", url: "", hotspot: [], position: { x: 32, y: 72 } },
      { loc: "R. Panel ", url: "", hotspot: [], position: { x: 28, y: 51.5 } },
      {
        loc: "R. Refraksi ",
        url: "",
        hotspot: [],
        position: { x: 35, y: 51.5 },
      },
      {
        loc: "R. Refraksi ",
        url: "",
        hotspot: [],
        position: { x: 35, y: 45.5 },
      },
      {
        loc: "IPSRS ",
        url: "",
        hotspot: [],
        position: { x: 35, y: 36.5 },
      },
      { loc: "R. Poli ", url: "", hotspot: [], position: { x: 46, y: 40 } },
      { loc: "R. Poli ", url: "", hotspot: [], position: { x: 52, y: 40 } },
      { loc: "NCT ", url: "", hotspot: [], position: { x: 56, y: 42.5 } },
      { loc: "R. TUNGGU ", url: "", hotspot: [], position: { x: 56, y: 66 } },
      { loc: "Oprimetri ", url: "", hotspot: [], position: { x: 56, y: 39 } },
      {
        loc: "R. Lensa Kontak ",
        url: "",
        hotspot: [],
        position: { x: 62, y: 39 },
      },
      {
        loc: "R. Alat Penunjang Diagnostik ",
        url: "",
        hotspot: [],
        position: { x: 70, y: 39 },
      },
      {
        loc: "Koridor  ",
        url: "",
        hotspot: [],
        position: { x: 82, y: 40 },
      },
      {
        loc: "Koridor  ",
        url: "",
        hotspot: [],
        position: { x: 82, y: 50 },
      },
      {
        loc: "R. Rawat Inap VIP  ",
        url: "",
        hotspot: [],
        position: { x: 85, y: 80 },
      },
      {
        loc: "Area Perawatan  ",
        url: "",
        hotspot: [],
        position: { x: 79, y: 80 },
      },
      {
        loc: "R. POLI ANAK  ",
        url: "",
        hotspot: [],
        position: { x: 70, y: 77.8 },
      },
      {
        loc: "R. POLI INTERNA  ",
        url: "",
        hotspot: [],
        position: { x: 70, y: 80.5 },
      },
    ],
  },

  {
    id: 2,
    name: "Lantai 3",
    denahUrl: "/panos/denah/Denah_lt3.jpeg",
    ruangan: [
      {
        loc: "ICU",
        url: "/panos/bernabue/bernabeu-1.jpg",
        hotspot: [],
        position: { x: 25, y: 32.5 },
      },
      {
        loc: "R. Recovery ",
        url: "/panos/bernabue/bernabeu-2.jpg",
        hotspot: [],
        position: { x: 32, y: 32.5 },
      },
      {
        loc: "OK 1",
        url: "/panos/bernabue/bernabeu-3.jpg",
        hotspot: [],
        position: { x: 39, y: 33.5 },
      },
      {
        loc: "OK 2",
        url: "/panos/bernabue/bernabeu-4.jpg",
        hotspot: [],
        position: { x: 50, y: 33.5 },
      },
      {
        loc: "OK 3",
        url: "/panos/bernabue/bernabeu-5.jpg",
        hotspot: [],
        position: { x: 58, y: 33.5 },
      },
      {
        loc: "OK 4",
        url: "/panos/bernabue/bernabeu-5.jpg",
        hotspot: [],
        position: { x: 69, y: 33.5 },
      },
      {
        loc: "KORIDOR OK ",
        url: "/panos/bernabue/bernabeu-5.jpg",
        hotspot: [],
        position: { x: 39, y: 45 },
      },
      {
        loc: "KORIDOR OK ",
        url: "/panos/bernabue/bernabeu-5.jpg",
        hotspot: [],
        position: { x: 39, y: 45 },
      },
      {
        loc: "KORIDOR OK ",
        url: "/panos/bernabue/bernabeu-5.jpg",
        hotspot: [],
        position: { x: 56.5, y: 45 },
      },
      {
        loc: "PREPARATION ",
        url: "/panos/bernabue/bernabeu-5.jpg",
        hotspot: [],
        position: { x: 44, y: 56 },
      },
      {
        loc: "R Ganti ",
        url: "/panos/bernabue/bernabeu-5.jpg",
        hotspot: [],
        position: { x: 61, y: 61 },
      },
      {
        loc: "R Steril Supply ",
        url: "/panos/bernabue/bernabeu-5.jpg",
        hotspot: [],
        position: { x: 70, y: 56 },
      },
      {
        loc: "R Steril Supply ",
        url: "/panos/bernabue/bernabeu-5.jpg",
        hotspot: [],
        position: { x: 75, y: 47 },
      },
      {
        loc: "R Packaging ",
        url: "/panos/bernabue/bernabeu-5.jpg",
        hotspot: [],
        position: { x: 83, y: 56 },
      },
      {
        loc: "R Inap Poli anak ",
        url: "/panos/bernabue/bernabeu-5.jpg",
        hotspot: [],
        position: { x: 83, y: 80 },
      },
      {
        loc: "Isolasi ",
        url: "/panos/bernabue/bernabeu-5.jpg",
        hotspot: [],
        position: { x: 90, y: 86 },
      },
      {
        loc: "Rawat Inap",
        url: "/panos/bernabue/bernabeu-1.jpg",
        hotspot: [],
        position: { x: 10, y: 55 },
      },
      {
        loc: "Rawat Inap",
        url: "/panos/bernabue/bernabeu-1.jpg",
        hotspot: [],
        position: { x: 8, y: 85 },
      },
      {
        loc: "Koridor ",
        url: "/panos/bernabue/bernabeu-1.jpg",
        hotspot: [],
        position: { x: 16, y: 76 },
      },
      {
        loc: "Pantry ",
        url: "/panos/bernabue/bernabeu-1.jpg",
        hotspot: [],
        position: { x: 31, y: 87 },
      },
      {
        loc: "R. Keluarga ",
        url: "/panos/bernabue/bernabeu-1.jpg",
        hotspot: [],
        position: { x: 35, y: 83.5 },
      },
    ],
  },

  {
    id: 3,
    name: "Lantai 4",
    denahUrl: "/panos/denah/Denah_lt3.jpeg",
    ruangan: [
      {
        loc: "lokasi 1",
        url: "/panos/Panorama-RsMata0.jpg",
        hotspot: [
          {
            yaw: -0.5,
            pitch: -0.1,
            label: "Rumah Sakit Mata Makassar",
            description: "Rumah Sakit Makassar Tallasa City",
          },
        ],
        hotspotNav: [
          {
            yaw: 1.2,
            pitch: -0.1,
            goto: "3-1",
          },
        ],
        position: { x: 22, y: 40 },
      },
      {
        loc: "lokasi 2",
        url: "/panos/Panorama-RsMata1.jpg",
        hotspot: [],
        hotspotNav: [
          {
            yaw: -1.2,
            pitch: -2.1,
            goto: "3-0",
          },
          {
            yaw: 0.4,
            pitch: 0.2,
            goto: "3-2",
          },
        ],
        position: { x: 40, y: 35 },
      },
      {
        loc: "lokasi 3",
        url: "/panos/Panorama-RsMata2.jpg",
        hotspot: [],
        hotspotNav: [
          {
            yaw: -0.5,
            pitch: -0.1,
            goto: "3-1",
          },
          {
            yaw: 0.4,
            pitch: 0.2,
            goto: "3-3",
          },
        ],
        position: { x: 55, y: 48 },
      },
      {
        loc: "lokasi 4",
        url: "/panos/Panorama-RsMata3.jpg",
        hotspot: [],
        hotspotNav: [
          {
            yaw: 1.2,
            pitch: -0.1,
            goto: "3-2",
          },
        ],
        position: { x: 10, y: 40 },
      },
    ],
  },
];
